// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchaseRequestSystem.Data;

#nullable disable

namespace PurchaseRequestSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PurchaseRequestSystem.Models.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tbl_account");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.ActivityLog", b =>
                {
                    b.Property<Guid>("ActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityLogId");

                    b.HasIndex("AccountId");

                    b.HasIndex("DocumentType", "DocumentId");

                    b.ToTable("tbl_activity_log");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.ApprovalRecord", b =>
                {
                    b.Property<Guid>("ApprovalRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApprovalStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProcurementRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApprovalRecordId");

                    b.HasIndex("ApprovalStageId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("StatusId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("ProcurementRequestId", "ApprovalStageId")
                        .IsUnique();

                    b.ToTable("tbl_approval_record");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.ApprovalStage", b =>
                {
                    b.Property<Guid>("ApprovalStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ApprovalStageId");

                    b.ToTable("tbl_approval_stage");

                    b.HasData(
                        new
                        {
                            ApprovalStageId = new Guid("33333333-3333-3333-3333-333333333301"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StageName = "Procure"
                        },
                        new
                        {
                            ApprovalStageId = new Guid("33333333-3333-3333-3333-333333333302"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StageName = "GM"
                        },
                        new
                        {
                            ApprovalStageId = new Guid("33333333-3333-3333-3333-333333333303"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StageName = "Chairman"
                        });
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyId");

                    b.HasIndex("CompanyCode")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tbl_company");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.GoodsReceipt", b =>
                {
                    b.Property<Guid>("GoodsReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiscrepancyNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodsReceiptNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HasDiscrepancy")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReceivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GoodsReceiptId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GoodsReceiptNo")
                        .IsUnique();

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("ReceivedBy");

                    b.HasIndex("StatusId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tbl_goods_receipt");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.GoodsReceiptDetail", b =>
                {
                    b.Property<Guid>("GoodsReceiptDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DetailNo")
                        .HasColumnType("int");

                    b.Property<string>("DiscrepancyType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GoodsReceiptAttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GoodsReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMatchPo")
                        .HasColumnType("bit");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PurchaseOrderDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ReceivedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GoodsReceiptDetailId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GoodsReceiptId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PurchaseOrderDetailId");

                    b.HasIndex("UomId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tbl_goods_receipt_detail");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Material", b =>
                {
                    b.Property<Guid>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MaterialId");

                    b.HasIndex("MaterialCode")
                        .IsUnique();

                    b.HasIndex("UomId");

                    b.ToTable("tbl_material");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.ProcurementRequest", b =>
                {
                    b.Property<Guid>("ProcurementRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProcurementRequestNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ProposalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("date");

                    b.Property<Guid>("RequestTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProcurementRequestId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProcurementRequestNo")
                        .IsUnique();

                    b.HasIndex("ProposalId");

                    b.HasIndex("RequestTypeId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tbl_procurement_request");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Proposal", b =>
                {
                    b.Property<Guid>("ProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProposalAttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProposalDate")
                        .HasColumnType("date");

                    b.Property<string>("ProposalNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProposalId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProposalNo")
                        .IsUnique();

                    b.HasIndex("RequesterId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tbl_proposal");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.ProposalDetail", b =>
                {
                    b.Property<Guid>("ProposalDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ApprovedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RequestedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("UomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProposalDetailId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProposalId");

                    b.HasIndex("UomId");

                    b.ToTable("tbl_proposal_detail");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.PurchaseOrder", b =>
                {
                    b.Property<Guid>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GrandtotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PoDate")
                        .HasColumnType("date");

                    b.Property<string>("PurchaseOrderAttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseOrderNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PurchaseOrderId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PurchaseOrderNo")
                        .IsUnique();

                    b.HasIndex("PurchaseRequestId")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("VendorId");

                    b.ToTable("tbl_purchase_order");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.PurchaseOrderDetail", b =>
                {
                    b.Property<Guid>("PurchaseOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DetailNo")
                        .HasColumnType("int");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PurchaseOrderDetailId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("UomId");

                    b.ToTable("tbl_purchase_order_detail");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.PurchaseOrderPayment", b =>
                {
                    b.Property<Guid>("PurchaseOrderPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("GoodsReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentProofPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentReferenceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PurchaseOrderPaymentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GoodsReceiptId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tbl_purchase_order_payment");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.PurchaseRequest", b =>
                {
                    b.Property<Guid>("PurchaseRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProcurementRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PurchaseRequestId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProcurementRequestId")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tbl_purchase_request");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.PurchaseRequestDetail", b =>
                {
                    b.Property<Guid>("PurchaseRequestDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("UomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PurchaseRequestDetailId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PurchaseRequestId");

                    b.HasIndex("UomId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tbl_purchase_request_detail");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.RequestType", b =>
                {
                    b.Property<Guid>("RequestTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RequestTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RequestTypeId");

                    b.HasIndex("RequestTypeCode")
                        .IsUnique();

                    b.ToTable("tbl_request_type");

                    b.HasData(
                        new
                        {
                            RequestTypeId = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Starts from an approved Proposal",
                            RequestTypeCode = "PROJECT",
                            RequestTypeName = "Project"
                        },
                        new
                        {
                            RequestTypeId = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Created directly by Procurement",
                            RequestTypeCode = "NON_PROJECT",
                            RequestTypeName = "Non-Project"
                        });
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleCode")
                        .IsUnique();

                    b.ToTable("tbl_role");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Creates proposals and project purchase requests",
                            RoleCode = "REQUESTER",
                            RoleName = "Requester"
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reviews proposals and creates non-project requests / POs",
                            RoleCode = "PROCURE",
                            RoleName = "Procurement"
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Approves purchase requests and records Chairman decisions",
                            RoleCode = "GM",
                            RoleName = "General Manager"
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Final offline approver",
                            RoleCode = "CHAIRMAN",
                            RoleName = "Chairman"
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111105"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Generates purchase orders",
                            RoleCode = "PROJECT_ADMIN",
                            RoleName = "Project Admin"
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111106"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System administrator",
                            RoleCode = "ADMIN",
                            RoleName = "Administrator"
                        });
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Status", b =>
                {
                    b.Property<Guid>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StatusId");

                    b.ToTable("tbl_status");

                    b.HasData(
                        new
                        {
                            StatusId = new Guid("44444444-4444-4444-4444-444444444401"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StatusName = "DRAFT"
                        },
                        new
                        {
                            StatusId = new Guid("44444444-4444-4444-4444-444444444402"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StatusName = "PENDING"
                        },
                        new
                        {
                            StatusId = new Guid("44444444-4444-4444-4444-444444444403"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StatusName = "SUBMITTED"
                        },
                        new
                        {
                            StatusId = new Guid("44444444-4444-4444-4444-444444444404"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StatusName = "UNDER_REVIEW"
                        },
                        new
                        {
                            StatusId = new Guid("44444444-4444-4444-4444-444444444405"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StatusName = "APPROVED"
                        },
                        new
                        {
                            StatusId = new Guid("44444444-4444-4444-4444-444444444406"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StatusName = "REJECTED"
                        },
                        new
                        {
                            StatusId = new Guid("44444444-4444-4444-4444-444444444407"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StatusName = "REVISION_REQUIRED"
                        },
                        new
                        {
                            StatusId = new Guid("44444444-4444-4444-4444-444444444408"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StatusName = "PARTIALLY_APPROVED"
                        },
                        new
                        {
                            StatusId = new Guid("44444444-4444-4444-4444-444444444409"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StatusName = "OPEN"
                        },
                        new
                        {
                            StatusId = new Guid("44444444-4444-4444-4444-444444444410"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StatusName = "PARTIALLY_RECEIVED"
                        },
                        new
                        {
                            StatusId = new Guid("44444444-4444-4444-4444-444444444411"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StatusName = "FULLY_RECEIVED"
                        },
                        new
                        {
                            StatusId = new Guid("44444444-4444-4444-4444-444444444412"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StatusName = "UNPAID"
                        },
                        new
                        {
                            StatusId = new Guid("44444444-4444-4444-4444-444444444413"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StatusName = "PARTIALLY_PAID"
                        },
                        new
                        {
                            StatusId = new Guid("44444444-4444-4444-4444-444444444414"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            StatusName = "PAID"
                        });
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Uom", b =>
                {
                    b.Property<Guid>("UomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UomCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UomId");

                    b.HasIndex("UomCode")
                        .IsUnique();

                    b.ToTable("tbl_uom");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.UserDetail", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("tbl_user_detail");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Vendor", b =>
                {
                    b.Property<Guid>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VendorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendorId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("VendorCode")
                        .IsUnique();

                    b.ToTable("tbl_vendor");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Account", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PurchaseRequestSystem.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.ActivityLog", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.ApprovalRecord", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.ApprovalStage", "ApprovalStage")
                        .WithMany("ApprovalRecords")
                        .HasForeignKey("ApprovalStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PurchaseRequestSystem.Models.ProcurementRequest", "ProcurementRequest")
                        .WithMany("ApprovalRecords")
                        .HasForeignKey("ProcurementRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovalStage");

                    b.Navigation("ProcurementRequest");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Company", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.GoodsReceipt", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PurchaseRequestSystem.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("ReceivedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.GoodsReceiptDetail", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PurchaseRequestSystem.Models.GoodsReceipt", "GoodsReceipt")
                        .WithMany("Details")
                        .HasForeignKey("GoodsReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.PurchaseOrderDetail", "PurchaseOrderDetail")
                        .WithMany("GoodsReceiptDetails")
                        .HasForeignKey("PurchaseOrderDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Uom", "Uom")
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GoodsReceipt");

                    b.Navigation("Material");

                    b.Navigation("PurchaseOrderDetail");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Material", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Uom", "Uom")
                        .WithMany("Materials")
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.ProcurementRequest", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PurchaseRequestSystem.Models.Proposal", "Proposal")
                        .WithMany("ProcurementRequests")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PurchaseRequestSystem.Models.RequestType", "RequestType")
                        .WithMany("ProcurementRequests")
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Proposal");

                    b.Navigation("RequestType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Proposal", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.ProposalDetail", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Proposal", "Proposal")
                        .WithMany("Details")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Uom", "Uom")
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Proposal");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.PurchaseOrder", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Company", "Company")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PurchaseRequestSystem.Models.PurchaseRequest", "PurchaseRequest")
                        .WithOne("PurchaseOrder")
                        .HasForeignKey("PurchaseRequestSystem.Models.PurchaseOrder", "PurchaseRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PurchaseRequestSystem.Models.Vendor", "Vendor")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("PurchaseRequest");

                    b.Navigation("Status");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.PurchaseOrderDetail", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Details")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Uom", "Uom")
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.PurchaseOrderPayment", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PurchaseRequestSystem.Models.GoodsReceipt", "GoodsReceipt")
                        .WithMany("Payments")
                        .HasForeignKey("GoodsReceiptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PurchaseRequestSystem.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Payments")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GoodsReceipt");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.PurchaseRequest", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PurchaseRequestSystem.Models.ProcurementRequest", "ProcurementRequest")
                        .WithOne("PurchaseRequest")
                        .HasForeignKey("PurchaseRequestSystem.Models.PurchaseRequest", "ProcurementRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProcurementRequest");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.PurchaseRequestDetail", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PurchaseRequestSystem.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.PurchaseRequest", "PurchaseRequest")
                        .WithMany("Details")
                        .HasForeignKey("PurchaseRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Uom", "Uom")
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Material");

                    b.Navigation("PurchaseRequest");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.UserDetail", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Account", "Account")
                        .WithOne("UserDetail")
                        .HasForeignKey("PurchaseRequestSystem.Models.UserDetail", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Vendor", b =>
                {
                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PurchaseRequestSystem.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Account", b =>
                {
                    b.Navigation("UserDetail");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.ApprovalStage", b =>
                {
                    b.Navigation("ApprovalRecords");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Company", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.GoodsReceipt", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.ProcurementRequest", b =>
                {
                    b.Navigation("ApprovalRecords");

                    b.Navigation("PurchaseRequest");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Proposal", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("ProcurementRequests");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.PurchaseOrder", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("GoodsReceipts");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.PurchaseOrderDetail", b =>
                {
                    b.Navigation("GoodsReceiptDetails");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.PurchaseRequest", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.RequestType", b =>
                {
                    b.Navigation("ProcurementRequests");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Uom", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("PurchaseRequestSystem.Models.Vendor", b =>
                {
                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
